# Change these first
owner: cxt666 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Menzer.net
    url: http://menzer.net
    icon: http://legacy.menzer.net/sites/default/files/dev.ico
  - name: TTRSS
    url: https://reader.mnzr.de
    __dangerous__disable_verify_peer: true
    icon: https://reader.mnzr.de/images/favicon.png
  - name: ubuntuusers.de
    url: https://ubuntuusers.de/
    icon: https://ubuntuusers.de/favicon.ico
  - name: ubuntuusers.de Forum
    url: https://forum.ubuntuusers.de/
    icon: https://ubuntuusers.de/favicon.ico
  - name: SURAS-DE
    url: https://de-emea-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-DE 2
    url: https://de-emea2-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-DE 3
    url: https://de-emea3-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-AP
    url: https://kr-ap-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-CN
    url: https://cn-ap-vpn.schaefflercn.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-IN
    url: https://in-ap-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-NA 1
    url: https://us-equ1-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-NA 2
    url: https://us-na2-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico
  - name: SURAS-BR
    url: https://br-sa-vpn.schaeffler.com/vpn
    icon: https://www.schaeffler.com/remotemedien/media/_shared_media/technik/images/addresser/favicon/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: stats.mnzr.de
  baseUrl: /upptime
  logoUrl: http://legacy.menzer.net/sites/default/files/dev-96x96.png #https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  favicon: http://legacy.menzer.net/sites/default/files/dev.ico
  name: menzer.net UppTime
  introTitle: "**menzer.net** Availability Monitoring"
  introMessage: This is a status page uses **real-time** data from our [GitHub repository](https://github.com/cxt666/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: dark # light, dark, ocean
  robotsText: "User-agent: * \n Disallow: /"
  user-agent: cxt666
  navbar:
    - title: Status
      href: /upptime
    - title: Root
      href: /
    - title: GitHub
      href: https://github.com/cxt666/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
